### ISSUE TITLE
features特征提取方式

### ISSUE THREAD

**Issue by hahaluluyo** [xjtupanda/AUW-GCN#1]
hello，感谢分享代码～
请问是该特征是采用什么方法提取的，在USTC_ME_Spotting特征上是如何modified的
期待您的回复

**Comment by xjtupanda** [comment]
1) 我们的工作基于MDMO特征，[A Main Directional Mean Optical Flow Feature for Spontaneous Micro-Expression Recognition](https://ieeexplore.ieee.org/document/7286757), [源代码连接](http://cg.cs.tsinghua.edu.cn/people/~Yongjin/variant_MDMO_code.zip).

2) 只是对USTC_ME_Spotting的特征文件进行了结构重排，没有对特征做修改。

**Comment by hahaluluyo** [comment]
在 2023-04-24 09:31:50，"xjtupanda" ***@***.***> 写道：

我们的工作基于MDMO特征，A Main Directional Mean Optical Flow Feature for Spontaneous Micro-Expression Recognition, 源代码连接.

只是对USTC_ME_Spotting的特征文件进行了结构重排，没有对特征做修改。

**Comment by xjtupanda** [comment]
自己实现的特征提取代码已经更新到本仓库。
