### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by flamefangz** [xjtupanda/AUW-GCN#7]
An error occurred when importing the models module. Is the module file missing?

**Comment by xjtupanda** [comment]
The missing files of the "SAN" package have been uploaded. It should be fine now.

**Comment by flamefangz** [comment]
Thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjtupanda/AUW-GCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月4日(星期一) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjtupanda/AUW-GCN] ModuleNotFoundError: No module named 'models' (Issue #7)





 
The missing files of the "SAN" package have been uploaded. It should be fine now.
